[package]
name = "newbase60-rs"
version = "0.1.0"
authors = ["Astrid Yu <astrid@astrid.tech>"]
edition = "2018"
license-file = "LICENSE"
homepage = "https://github.com/Plenglin/newbase60-rs"
repository = "https://github.com/Plenglin/newbase60-rs"
description = "A library that implements Tantek Celik's New Base 60"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rstest = "0.7.0"
