[package]
name = "newbase60-rs"
version = "0.1.0"
authors = ["Astrid Yu <astrid@astrid.tech>"]
edition = "2018"
license = "MIT"
license-file = "LICENSE"
homepage = ""
description = "A library that implements Tantek Celik's New Base 60"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
