name: Rust

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login
        run: cargo login ${{secrets.API_TOKEN}}

      - name: Publish
        run: cargo publish